// Code generated by protoc-gen-go. DO NOT EDIT.
// source: search.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SearchRequest struct {
	Word                 string   `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Sort                 int32    `protobuf:"varint,3,opt,name=sort,proto3" json:"sort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{0}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetWord() string {
	if m != nil {
		return m.Word
	}
	return ""
}

func (m *SearchRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SearchRequest) GetSort() int32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

type Result struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Lang                 uint32   `protobuf:"varint,4,opt,name=lang,proto3" json:"lang,omitempty"`
	Favicon              string   `protobuf:"bytes,5,opt,name=favicon,proto3" json:"favicon,omitempty"`
	IsTop5               bool     `protobuf:"varint,6,opt,name=isTop5,proto3" json:"isTop5,omitempty"`
	Star                 int32    `protobuf:"varint,7,opt,name=star,proto3" json:"star,omitempty"`
	TimeStamp            uint32   `protobuf:"varint,8,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	Description          string   `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{1}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Result) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Result) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Result) GetLang() uint32 {
	if m != nil {
		return m.Lang
	}
	return 0
}

func (m *Result) GetFavicon() string {
	if m != nil {
		return m.Favicon
	}
	return ""
}

func (m *Result) GetIsTop5() bool {
	if m != nil {
		return m.IsTop5
	}
	return false
}

func (m *Result) GetStar() int32 {
	if m != nil {
		return m.Star
	}
	return 0
}

func (m *Result) GetTimeStamp() uint32 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func (m *Result) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type SearchResponse struct {
	Data                 []*Result `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Keywords             []string  `protobuf:"bytes,2,rep,name=keywords,proto3" json:"keywords,omitempty"`
	Success              bool      `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Total                uint32    `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{2}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetData() []*Result {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SearchResponse) GetKeywords() []string {
	if m != nil {
		return m.Keywords
	}
	return nil
}

func (m *SearchResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SearchResponse) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type DetailRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetailRequest) Reset()         { *m = DetailRequest{} }
func (m *DetailRequest) String() string { return proto.CompactTextString(m) }
func (*DetailRequest) ProtoMessage()    {}
func (*DetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{3}
}

func (m *DetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailRequest.Unmarshal(m, b)
}
func (m *DetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailRequest.Marshal(b, m, deterministic)
}
func (m *DetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailRequest.Merge(m, src)
}
func (m *DetailRequest) XXX_Size() int {
	return xxx_messageInfo_DetailRequest.Size(m)
}
func (m *DetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DetailRequest proto.InternalMessageInfo

func (m *DetailRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DetailResponse struct {
	Data                 *Result  `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetailResponse) Reset()         { *m = DetailResponse{} }
func (m *DetailResponse) String() string { return proto.CompactTextString(m) }
func (*DetailResponse) ProtoMessage()    {}
func (*DetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{4}
}

func (m *DetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailResponse.Unmarshal(m, b)
}
func (m *DetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailResponse.Marshal(b, m, deterministic)
}
func (m *DetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailResponse.Merge(m, src)
}
func (m *DetailResponse) XXX_Size() int {
	return xxx_messageInfo_DetailResponse.Size(m)
}
func (m *DetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DetailResponse proto.InternalMessageInfo

func (m *DetailResponse) GetData() *Result {
	if m != nil {
		return m.Data
	}
	return nil
}

type DetailsRequest struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetailsRequest) Reset()         { *m = DetailsRequest{} }
func (m *DetailsRequest) String() string { return proto.CompactTextString(m) }
func (*DetailsRequest) ProtoMessage()    {}
func (*DetailsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{5}
}

func (m *DetailsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailsRequest.Unmarshal(m, b)
}
func (m *DetailsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailsRequest.Marshal(b, m, deterministic)
}
func (m *DetailsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailsRequest.Merge(m, src)
}
func (m *DetailsRequest) XXX_Size() int {
	return xxx_messageInfo_DetailsRequest.Size(m)
}
func (m *DetailsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DetailsRequest proto.InternalMessageInfo

func (m *DetailsRequest) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type DetailsResponse struct {
	Data                 []*Result `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DetailsResponse) Reset()         { *m = DetailsResponse{} }
func (m *DetailsResponse) String() string { return proto.CompactTextString(m) }
func (*DetailsResponse) ProtoMessage()    {}
func (*DetailsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{6}
}

func (m *DetailsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailsResponse.Unmarshal(m, b)
}
func (m *DetailsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailsResponse.Marshal(b, m, deterministic)
}
func (m *DetailsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailsResponse.Merge(m, src)
}
func (m *DetailsResponse) XXX_Size() int {
	return xxx_messageInfo_DetailsResponse.Size(m)
}
func (m *DetailsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DetailsResponse proto.InternalMessageInfo

func (m *DetailsResponse) GetData() []*Result {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*SearchRequest)(nil), "search.SearchRequest")
	proto.RegisterType((*Result)(nil), "search.Result")
	proto.RegisterType((*SearchResponse)(nil), "search.SearchResponse")
	proto.RegisterType((*DetailRequest)(nil), "search.DetailRequest")
	proto.RegisterType((*DetailResponse)(nil), "search.DetailResponse")
	proto.RegisterType((*DetailsRequest)(nil), "search.DetailsRequest")
	proto.RegisterType((*DetailsResponse)(nil), "search.DetailsResponse")
}

func init() {
	proto.RegisterFile("search.proto", fileDescriptor_453745cff914010e)
}

var fileDescriptor_453745cff914010e = []byte{
	// 420 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0xc5, 0x4d, 0x9b, 0x26, 0xb3, 0xb4, 0xac, 0x46, 0x50, 0xac, 0x0a, 0x89, 0xc8, 0xa7, 0x9c,
	0xf6, 0xb0, 0xb0, 0x87, 0x95, 0x38, 0x21, 0x6e, 0xdc, 0xbc, 0x9c, 0xb8, 0x99, 0xc4, 0x2c, 0x16,
	0xd9, 0x38, 0xd8, 0x0e, 0x88, 0x1b, 0x5f, 0xc6, 0x87, 0xf0, 0x35, 0xc8, 0x76, 0x9c, 0xa5, 0xad,
	0x90, 0xf6, 0xd4, 0xf7, 0x5e, 0x67, 0xde, 0xcc, 0xbc, 0x24, 0xf0, 0xd8, 0x4a, 0x61, 0x9a, 0x2f,
	0x17, 0x83, 0xd1, 0x4e, 0x63, 0x1e, 0x19, 0x7b, 0x0f, 0x9b, 0x9b, 0x80, 0xb8, 0xfc, 0x36, 0x4a,
	0xeb, 0x10, 0x61, 0xf9, 0x43, 0x9b, 0x96, 0x92, 0x8a, 0xd4, 0x25, 0x0f, 0xd8, 0x6b, 0x83, 0xb8,
	0x95, 0x74, 0x51, 0x91, 0x7a, 0xc5, 0x03, 0xf6, 0x9a, 0xd5, 0xc6, 0xd1, 0x2c, 0x6a, 0x1e, 0xb3,
	0x3f, 0x04, 0x72, 0x2e, 0xed, 0xd8, 0x39, 0xdc, 0xc2, 0x42, 0x25, 0x93, 0x85, 0x6a, 0xf1, 0x29,
	0xac, 0x9c, 0x72, 0x5d, 0xf4, 0x28, 0x79, 0x24, 0x78, 0x0e, 0xd9, 0x68, 0xba, 0xe0, 0x51, 0x72,
	0x0f, 0xbd, 0x6d, 0x27, 0xfa, 0x5b, 0xba, 0xac, 0x48, 0xbd, 0xe1, 0x01, 0x23, 0x85, 0xf5, 0x67,
	0xf1, 0x5d, 0x35, 0xba, 0xa7, 0xab, 0x50, 0x99, 0x28, 0xee, 0x20, 0x57, 0xf6, 0x83, 0x1e, 0xae,
	0x68, 0x5e, 0x91, 0xba, 0xe0, 0x13, 0x0b, 0xcb, 0x39, 0x61, 0xe8, 0x7a, 0x5a, 0xce, 0x09, 0x83,
	0x2f, 0xa0, 0x74, 0xea, 0x4e, 0xde, 0x38, 0x71, 0x37, 0xd0, 0x22, 0xd8, 0xdf, 0x0b, 0x58, 0xc1,
	0x59, 0x2b, 0x6d, 0x63, 0xd4, 0xe0, 0x94, 0xee, 0x69, 0x19, 0xe6, 0xfc, 0x2b, 0xb1, 0x5f, 0x04,
	0xb6, 0x29, 0x2a, 0x3b, 0xe8, 0xde, 0x4a, 0x64, 0xb0, 0x6c, 0x85, 0x13, 0x94, 0x54, 0x59, 0x7d,
	0x76, 0xb9, 0xbd, 0x98, 0x12, 0x8e, 0x11, 0xf0, 0xf0, 0x1f, 0xee, 0xa1, 0xf8, 0x2a, 0x7f, 0xfa,
	0x18, 0x2d, 0x5d, 0x54, 0x59, 0x5d, 0xf2, 0x99, 0xfb, 0xc3, 0xec, 0xd8, 0x34, 0xd2, 0xda, 0x10,
	0x41, 0xc1, 0x13, 0x0d, 0x71, 0x69, 0x27, 0xba, 0x29, 0x87, 0x48, 0xd8, 0x4b, 0xd8, 0xbc, 0x93,
	0x4e, 0xa8, 0x2e, 0x3d, 0xac, 0xa3, 0x94, 0xd9, 0x6b, 0xd8, 0xa6, 0x82, 0x93, 0x15, 0xc9, 0xff,
	0x56, 0x64, 0x2c, 0x75, 0xd9, 0xe4, 0x7b, 0x0e, 0x99, 0x6a, 0x6d, 0xb8, 0xab, 0xe4, 0x1e, 0xb2,
	0x2b, 0x78, 0x32, 0xd7, 0x3c, 0xfc, 0xfa, 0xcb, 0xdf, 0x04, 0x8a, 0x18, 0x9a, 0x34, 0x78, 0x0d,
	0x79, 0xc4, 0xf8, 0x2c, 0x15, 0x1f, 0xbc, 0x7b, 0xfb, 0xdd, 0xb1, 0x1c, 0x27, 0xb1, 0x47, 0xf8,
	0x06, 0xd6, 0xd3, 0x78, 0x9c, 0x8b, 0x0e, 0x77, 0xde, 0x3f, 0x3f, 0xd1, 0xe7, 0xee, 0x6b, 0xc8,
	0xa3, 0x78, 0x3f, 0xf8, 0x20, 0xc7, 0xfd, 0xee, 0x58, 0x4e, 0xad, 0x6f, 0xd7, 0x1f, 0x57, 0xe1,
	0x83, 0xf9, 0x94, 0x87, 0x9f, 0x57, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x51, 0x16, 0xec, 0x4a,
	0x47, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SearcherClient is the client API for Searcher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SearcherClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	Details(ctx context.Context, in *DetailsRequest, opts ...grpc.CallOption) (*DetailsResponse, error)
	Detail(ctx context.Context, in *DetailRequest, opts ...grpc.CallOption) (*DetailResponse, error)
}

type searcherClient struct {
	cc grpc.ClientConnInterface
}

func NewSearcherClient(cc grpc.ClientConnInterface) SearcherClient {
	return &searcherClient{cc}
}

func (c *searcherClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/search.Searcher/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searcherClient) Details(ctx context.Context, in *DetailsRequest, opts ...grpc.CallOption) (*DetailsResponse, error) {
	out := new(DetailsResponse)
	err := c.cc.Invoke(ctx, "/search.Searcher/Details", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searcherClient) Detail(ctx context.Context, in *DetailRequest, opts ...grpc.CallOption) (*DetailResponse, error) {
	out := new(DetailResponse)
	err := c.cc.Invoke(ctx, "/search.Searcher/Detail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearcherServer is the server API for Searcher service.
type SearcherServer interface {
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	Details(context.Context, *DetailsRequest) (*DetailsResponse, error)
	Detail(context.Context, *DetailRequest) (*DetailResponse, error)
}

// UnimplementedSearcherServer can be embedded to have forward compatible implementations.
type UnimplementedSearcherServer struct {
}

func (*UnimplementedSearcherServer) Search(ctx context.Context, req *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (*UnimplementedSearcherServer) Details(ctx context.Context, req *DetailsRequest) (*DetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Details not implemented")
}
func (*UnimplementedSearcherServer) Detail(ctx context.Context, req *DetailRequest) (*DetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Detail not implemented")
}

func RegisterSearcherServer(s *grpc.Server, srv SearcherServer) {
	s.RegisterService(&_Searcher_serviceDesc, srv)
}

func _Searcher_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearcherServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.Searcher/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearcherServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Searcher_Details_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearcherServer).Details(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.Searcher/Details",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearcherServer).Details(ctx, req.(*DetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Searcher_Detail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearcherServer).Detail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.Searcher/Detail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearcherServer).Detail(ctx, req.(*DetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Searcher_serviceDesc = grpc.ServiceDesc{
	ServiceName: "search.Searcher",
	HandlerType: (*SearcherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _Searcher_Search_Handler,
		},
		{
			MethodName: "Details",
			Handler:    _Searcher_Details_Handler,
		},
		{
			MethodName: "Detail",
			Handler:    _Searcher_Detail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "search.proto",
}
