// Code generated by protoc-gen-go. DO NOT EDIT.
// source: star.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StarRequest struct {
	Word                 string   `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	Type                 int32    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	DocId                string   `protobuf:"bytes,3,opt,name=docId,proto3" json:"docId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StarRequest) Reset()         { *m = StarRequest{} }
func (m *StarRequest) String() string { return proto.CompactTextString(m) }
func (*StarRequest) ProtoMessage()    {}
func (*StarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf02c9100040aa, []int{0}
}

func (m *StarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StarRequest.Unmarshal(m, b)
}
func (m *StarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StarRequest.Marshal(b, m, deterministic)
}
func (m *StarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StarRequest.Merge(m, src)
}
func (m *StarRequest) XXX_Size() int {
	return xxx_messageInfo_StarRequest.Size(m)
}
func (m *StarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StarRequest proto.InternalMessageInfo

func (m *StarRequest) GetWord() string {
	if m != nil {
		return m.Word
	}
	return ""
}

func (m *StarRequest) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *StarRequest) GetDocId() string {
	if m != nil {
		return m.DocId
	}
	return ""
}

type StarResponse struct {
	IsSuccess            bool     `protobuf:"varint,1,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StarResponse) Reset()         { *m = StarResponse{} }
func (m *StarResponse) String() string { return proto.CompactTextString(m) }
func (*StarResponse) ProtoMessage()    {}
func (*StarResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf02c9100040aa, []int{1}
}

func (m *StarResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StarResponse.Unmarshal(m, b)
}
func (m *StarResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StarResponse.Marshal(b, m, deterministic)
}
func (m *StarResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StarResponse.Merge(m, src)
}
func (m *StarResponse) XXX_Size() int {
	return xxx_messageInfo_StarResponse.Size(m)
}
func (m *StarResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StarResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StarResponse proto.InternalMessageInfo

func (m *StarResponse) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func init() {
	proto.RegisterType((*StarRequest)(nil), "star.StarRequest")
	proto.RegisterType((*StarResponse)(nil), "star.StarResponse")
}

func init() {
	proto.RegisterFile("star.proto", fileDescriptor_3eaf02c9100040aa)
}

var fileDescriptor_3eaf02c9100040aa = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2e, 0x49, 0x2c,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0xbc, 0xb9, 0xb8, 0x83, 0x4b,
	0x12, 0x8b, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x84, 0xb8, 0x58, 0xca, 0xf3, 0x8b,
	0x52, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x90, 0x58, 0x49, 0x65, 0x41, 0xaa,
	0x04, 0x93, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x98, 0x2d, 0x24, 0xc2, 0xc5, 0x9a, 0x92, 0x9f, 0xec,
	0x99, 0x22, 0xc1, 0x0c, 0x56, 0x08, 0xe1, 0x28, 0xe9, 0x70, 0xf1, 0x40, 0x0c, 0x2b, 0x2e, 0xc8,
	0xcf, 0x2b, 0x4e, 0x15, 0x92, 0xe1, 0xe2, 0xcc, 0x2c, 0x0e, 0x2e, 0x4d, 0x4e, 0x4e, 0x2d, 0x2e,
	0x06, 0x1b, 0xc9, 0x11, 0x84, 0x10, 0x30, 0xb2, 0xe4, 0x62, 0x03, 0xa9, 0x4e, 0x2d, 0x12, 0xd2,
	0xe7, 0x62, 0x01, 0xb1, 0x84, 0x04, 0xf5, 0xc0, 0xee, 0x43, 0x72, 0x90, 0x94, 0x10, 0xb2, 0x10,
	0xc4, 0x58, 0x25, 0x06, 0x27, 0xf6, 0x28, 0x56, 0xb0, 0x27, 0x92, 0xd8, 0xc0, 0x94, 0x31, 0x20,
	0x00, 0x00, 0xff, 0xff, 0xe5, 0xf8, 0xcc, 0x17, 0xd9, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StarerClient is the client API for Starer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StarerClient interface {
	Star(ctx context.Context, in *StarRequest, opts ...grpc.CallOption) (*StarResponse, error)
}

type starerClient struct {
	cc grpc.ClientConnInterface
}

func NewStarerClient(cc grpc.ClientConnInterface) StarerClient {
	return &starerClient{cc}
}

func (c *starerClient) Star(ctx context.Context, in *StarRequest, opts ...grpc.CallOption) (*StarResponse, error) {
	out := new(StarResponse)
	err := c.cc.Invoke(ctx, "/star.Starer/Star", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StarerServer is the server API for Starer service.
type StarerServer interface {
	Star(context.Context, *StarRequest) (*StarResponse, error)
}

// UnimplementedStarerServer can be embedded to have forward compatible implementations.
type UnimplementedStarerServer struct {
}

func (*UnimplementedStarerServer) Star(ctx context.Context, req *StarRequest) (*StarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Star not implemented")
}

func RegisterStarerServer(s *grpc.Server, srv StarerServer) {
	s.RegisterService(&_Starer_serviceDesc, srv)
}

func _Starer_Star_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarerServer).Star(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/star.Starer/Star",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarerServer).Star(ctx, req.(*StarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Starer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "star.Starer",
	HandlerType: (*StarerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Star",
			Handler:    _Starer_Star_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "star.proto",
}
